version: "3.3"
services:
  solaredge_meterproxy:
    build: .
    image: solaredge_meterproxy
    ports:
     - "192.168.20.12:5502:5502"
    restart: unless-stopped
    container_name: solaredge_meterproxy
