version: "3.3"
services:
  solaredge_meterproxy:
    build: .
    image: solaredge_meterproxy
    devices:
     - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    container_name: solaredge_meterproxy
